sudo: required
language: perl6
perl6:
    - latest
before_install:
    - curl -L http://cpanmin.us | sudo perl - --self-upgrade
    - sudo cpanm install WebService::UrbanDictionary
install:
    - rakudobrew build-panda
    - panda installdeps .
    - panda install IRC::Client
