sudo: required
language: perl6
perl6:
    - latest
before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y install perlbrew
    - travis_wait perlbrew install -Duseshrplib --thread --multi -j $(nproc) perl-5.20.0
    - perlbrew switch perl-5.20.0
    - perlbrew -f install-cpanm
    - cpanm install WebService::UrbanDictionary
install:
    - rakudobrew build-panda
    - panda --notest installdeps .
    - panda --notest install IRC::Client
    - panda --notest install Inline::Perl5
